Feature/word level progress tracking
capacitor-community/text-to-speech pull request #132
Opened 2024-07-10 07:05 UTC by Dhruv-1105

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.

2024-07-12 07:57 UTC, robingenz requested changes

2024-07-12 07:57 UTC, robingenz commented on CHANGELOG.md
Please revert the changes in this file.

2024-07-12 07:57 UTC, robingenz commented on package.json
Please revert this change.

2024-07-12 07:57 UTC, robingenz commented on package-lock.json
Please revert this change.

2024-07-16 04:36 UTC, Dhruv-1105 commented
I have updated the commit as per changes requested. Please check and test it.

2024-07-17 07:09 UTC, robingenz approved these changes

2024-07-17 07:12 UTC, robingenz commented
Please fix the workflow errors.

2024-07-17 07:23 UTC, robingenz approved these changes

2024-07-17 07:41 UTC, merged